#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <crypt.h>

#define MAX_SIZE 20

/*
	Allows to crack a hash generated by crypt function.
	It works for Linux shadow passwords, just give the
	salt, the remainder of the hash and a wordlist.
	
	To compile with gcc:
	gcc -o cracklinux cracklinux.c -lcrypt
*/

void copy(char * dest, char * src, int len);

int main(int argc, char *argv[]){
	if(argc < 4){
		printf("USAGE: %s <salt> <hash> <wordlist>\n", argv[0]);
		exit(1);
	}

	char salt[25];
	char hash[100];
	char hashandsalt[150];
	char *buff;

	strcpy(salt, argv[1]);
	strcpy(hash, argv[2]);
	strcpy(hashandsalt, salt);
	strcat(hashandsalt, hash);

	FILE *wordlist = fopen(argv[3], "r");

	while(fgets(buff, MAX_SIZE, wordlist)){
		char buffer[MAX_SIZE];
		copy(buffer, buff, MAX_SIZE); // removes the final '\n'

		if(buffer[0] != '\0'){
			if(!(strcmp(crypt(buffer, salt), hashandsalt))){
				printf("+=========================+\n");
				printf("KEY FOUND! %s\n", buffer);
				printf("+=========================+\n");
				fclose(wordlist);
				return 0;
			}else{
				printf("Trying %s...\n", buffer);
			}
		}
	}

	printf("The key could not be found :(\n");
	fclose(wordlist);
	return 1;
}

void copy(char * dest, char * src, int len){
	int i = 0;

	while(i < len){
		if(src[i] != '\n')
			dest[i] = src[i];
		else
			dest[i] = '\0';
		i++;
	}
}
